### PR TITLE
Updated Background

### PR DESCRIPTION
**Pull request by dhruvaop**
Updated Background in CSS and changes in index.html

### CODE REVIEW

**Review by Nitesh-thapliyal — APPROVED** [review]

**Comment by Nitesh-thapliyal** [comment]
> Updated Background in CSS and changes in index.html

Can you share snapshot of changes made

**Review by kevalvavaliya — CHANGES_REQUESTED** [review]
@dhruvaop can you share the snapshots

**Comment by dhruvaop** [comment]
Screenshot (137)
Screenshot (139)

**Comment by adityamangal1** [comment]
@dhruvaop Can you resolve conflicts

**Comment by dhruvaop** [comment]
@adityamangal1 Its's working on my localhost properly no issues

**Comment by adityamangal1** [comment]
> @adityamangal1 Its's working on my localhost properly no issues

I'm talking about conflicts not about code

**Comment by adityamangal1** [comment]
> @adityamangal1 Its's working on my localhost properly no issues

Check out thia guide to know more about conflicts and how to resolve https://www.gitkraken.com/learn/git/tutorials/how-to-resolve-merge-conflict-in-git

**Comment by dhruvaop** [comment]
@adityamangal1 done please check

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
